---
dependency:
  name: galaxy

driver:
  name: docker

platforms:
  - name: instance-ubuntu
    image: ubuntu:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/lib/systemd/systemd"
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN

  - name: instance-oraclelinux
    image: oraclelinux:8
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    command: "/usr/sbin/init"
    tmpfs:
      - /tmp
      - /run
    capabilities:
      - SYS_ADMIN

ansible:
  cfg:
    defaults:
      host_key_checking: false
      pipelining: true
  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --diff
        - --force-handlers
  playbooks:
    converge: converge.yml
    verify: verify.yml

scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - prepare
    - converge
    - idempotence
    - side_effect
    - verify
    - cleanup
    - destroy
