---
- name: Prepare
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Install python3 for Ubuntu
      ansible.builtin.apt:
        name: python3
        state: present
        update_cache: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Install python3 for OracleLinux
      ansible.builtin.yum:
        name: python3
        state: present
      when: ansible_facts['os_family'] == "RedHat"

